### ISSUE TITLE
electricity_demand_etrago.export-to-db fails in the first try

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#112]
The task electricity_demand_etrago.export-to-db is failing in test mode (probably also for DE). It runs ok once it is cleared. The log says: 

Traceback (most recent call last):
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/__init__.py", line 204, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/electricity_demand_etrago.py", line 207, in export_to_db
    curves = demands_per_bus(scenario)
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/electricity_demand_etrago.py", line 66, in demands_per_bus
    hh_curves = db.select_dataframe(
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/db.py", line 188, in select_dataframe
    df = pd.read_sql(sql, engine(), index_col=index_col)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 628, in read_sql
    return pandas_sql.read_query(
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 1579, in read_query
    result = self.execute(*args)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 1424, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "demand.egon_etrago_electricity_households" does not exist
LINE 2:                 demand.
                        ^

[SQL: SELECT bus_id, p_set FROM
                demand.
                egon_etrago_electricity_households
                WHERE scn_name = 'status2019']
(Background on this error at: http://sqlalche.me/e/13/f405)
[2023-07-06 16:45:43,085] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=powerd-status-quo-processing-pipeline, task_id=electricity_demand_etrago.export-to-db, execution_date=20230706T134214, start_date=20230706T144540, end_date=20230706T144543
[2023-07-06 16:45:45,722] {local_task_job.py:102} INFO - Task exited with return code 1 

It is likely due to a dependency problem.

**Comment by CarlosEpia** [comment]
This error was not present anymore after updating airflow (or at least at that point I realized it). This issue can be closed.
