### ISSUE TITLE
Task district_heating_areas.demarcation is failing

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#134]
The task district_heating_areas.demarcation is failing when running the airflow. Error message:

[2023-10-17, 11:48:05 UTC] {logging_mixin.py:149} INFO - Minimum heat demand density for cells with new district heat
          supply in scenario status2019 is
          1758.5524800328956
          MWh / (ha a).
[2023-10-17, 11:48:05 UTC] {logging_mixin.py:149} INFO - Number of cells with new district heat supply in scenario
          status2019 is 12781.
[2023-10-17, 11:48:16 UTC] {logging_mixin.py:149} WARNING - /home/powerd/clean-run-powerd-***/powerd-***/src/egon/***/***sets/district_heating_areas/__init__.py:1161 FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
[2023-10-17, 11:48:20 UTC] {logging_mixin.py:149} WARNING - /home/powerd/clean-run-powerd-***/powerd-***/src/egon/***/***sets/district_heating_areas/__init__.py:1161 FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
[2023-10-17, 11:48:21 UTC] {logging_mixin.py:149} INFO - 0        8783667.0
1        8721593.0
2        8712697.0
3        9019915.0
4        8814684.0
           ...    
75841          NaN
75842          NaN
75843          NaN
75844          NaN
75845          NaN
Name: zensus_population_id, Length: 75846, dtype: float64
[2023-10-17, 11:48:21 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/powerd/clean-run-powerd-data/powerd-data/src/egon/data/datasets/__init__.py", line 204, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/powerd/clean-run-powerd-data/powerd-data/src/egon/data/datasets/district_heating_areas/__init__.py", line 1161, in demarcation
    heat_density_per_scenario[scenario] = district_heating_areas(
  File "/home/powerd/clean-run-powerd-data/powerd-data/src/egon/data/datasets/district_heating_areas/__init__.py", line 618, in district_heating_areas
    scenario_dh_area.loc[:, "zensus_population_id"] = scenario_dh_area.loc[
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 105, in _astype_nansafe
    return _astype_float_to_int_nansafe(arr, dtype, copy)
  File "/home/powerd/clean-run-powerd-data/venv262/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 150, in _astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
[2023-10-17, 11:48:21 UTC] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=powerd-status-quo-processing-pipeline, task_id=district_heating_areas.demarcation, execution_date=20230928T071801, start_date=20231017T111208, end_date=20231017T114821
[2023-10-17, 11:48:21 UTC] {standard_task_runner.py:104} ERROR - Failed to execute job 96 for task district_heating_areas.demarcation (Cannot convert non-finite values (NA or inf) to integer; 3744497)
[2023-10-17, 11:48:22 UTC] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-17, 11:48:22 UTC] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check

**Comment by CarlosEpia** [comment]
I see that you have some experience working with this script. Can I assign this issue to you @ClaraBuettner?
