### ISSUE TITLE
heat_demand_timeseries.district-heating is failing

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#161]
The task heat_demand_timeseries.district-heating fails in the new powerD-data run with the error message pasted below. It was already cleared once with the same result.

[2023-11-30, 15:10:55 UTC] {logging_mixin.py:154} INFO - WARNING: No *** returned by statement: 
 
            SELECT a.zensus_population_id, building_id, c.climate_zone,
            selected_idp, ordinality as day, b.area_id
            FROM demand.egon_heat_timeseries_selected_profiles a
            INNER JOIN boundaries.egon_map_zensus_climate_zones c
            ON a.zensus_population_id = c.zensus_population_id
            INNER JOIN (
                SELECT * FROM demand.egon_map_zensus_district_heating_areas
                WHERE scenario = 'status2019'
                AND area_id = '1862'
            ) b ON a.zensus_population_id = b.zensus_population_id        ,
    
            UNNEST (selected_idp_profiles) WITH ORDINALITY as selected_idp
    
            
[2023-11-30, 15:16:28 UTC] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/powerd/clean-run-powerd-data/powerd-data/src/egon/data/datasets/__init__.py", line 204, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/powerd/clean-run-powerd-data/powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/powerd/clean-run-powerd-data/powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/powerd/clean-run-powerd-data/powerd-data/src/egon/data/datasets/heat_demand_timeseries/__init__.py", line 794, in district_heating
    create_district_heating_profile_python_like(scenario)
  File "/home/powerd/clean-run-powerd-data/powerd-data/src/egon/data/datasets/heat_demand_timeseries/__init__.py", line 364, in create_district_heating_profile_python_like
    assert (
AssertionError: Deviation of residential heat demand time 
            series for district heating grid 2101 is 0.1051602051049919
[2023-11-30, 15:16:28 UTC] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=powerd-status-quo-processing-pipeline, task_id=heat_demand_timeseries.district-heating, execution_date=20231127T105639, start_date=20231130T124352, end_date=20231130T151628
[2023-11-30, 15:16:28 UTC] {standard_task_runner.py:104} ERROR - Failed to execute job 126 for task heat_demand_timeseries.district-heating (Deviation of residential heat demand time 
            series for district heating grid 2101 is 0.1051602051049919; 3870566)
[2023-11-30, 15:16:28 UTC] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30, 15:16:28 UTC] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check

**Comment by CarlosEpia** [comment]
Seems to be a problem related to a previous task already solved.
