### ISSUE TITLE
entsoe-py parsing-error

### ISSUE THREAD

**Issue by iuljan** [openego/powerd-data#177]
`client.query_installed_generation_capacity()` failed due to some parsing-issues. 
See the log:
```
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/julian.endres/.config/JetBrains/PyCharm2023.2/scratches/foreign_neighbours.py", line 136, in <module>
    a = entsoe_historic_generation_capacities()
  File "/home/local/RL-INSTITUT/julian.endres/.config/JetBrains/PyCharm2023.2/scratches/foreign_neighbours.py", line 53, in entsoe_historic_generation_capacities
    client.query_installed_generation_capacity(country, **kwargs)
  File "/home/local/RL-INSTITUT/julian.endres/miniconda3/envs/powerd-data/lib/python3.8/site-packages/entsoe/decorators.py", line 100, in year_wrapper
    frame = func(*args, start=_start, end=_end, **kwargs)
  File "/home/local/RL-INSTITUT/julian.endres/miniconda3/envs/powerd-data/lib/python3.8/site-packages/entsoe/entsoe.py", line 1381, in query_installed_generation_capacity
    df = parse_generation(text)
  File "/home/local/RL-INSTITUT/julian.endres/miniconda3/envs/powerd-data/lib/python3.8/site-packages/entsoe/parsers.py", line 138, in parse_generation
    ts = _parse_generation_timeseries(soup, per_plant=per_plant, include_eic=include_eic)
  File "/home/local/RL-INSTITUT/julian.endres/miniconda3/envs/powerd-data/lib/python3.8/site-packages/entsoe/parsers.py", line 751, in _parse_generation_timeseries
    series.index = _parse_datetimeindex(soup)
  File "/home/local/RL-INSTITUT/julian.endres/miniconda3/envs/powerd-data/lib/python3.8/site-packages/entsoe/parsers.py", line 879, in _parse_datetimeindex
    elif pd.Timedelta(delta) >= pd.Timedelta('1D') and end.hour == start.hour + 1:
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1766, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "pandas/_libs/tslibs/timedeltas.pyx", line 646, in pandas._libs.tslibs.timedeltas.parse_timedelta_string
  File "pandas/_libs/tslibs/timedeltas.pyx", line 694, in pandas._libs.tslibs.timedeltas.timedelta_from_spec
ValueError: Units 'M', 'Y' and 'y' do not represent unambiguous timedelta values and are not supported.
```

**Comment by nailend** [comment]
Solved by upgrading entsoe-py to latest version but would guess at least to [v0.6](https://github.com/EnergieID/entsoe-py/releases/tag/V0.6.0), due to some refactoring in the generic parsing of timeseries

**Comment by iuljan** [comment]
Solved by upgrading entsoe-py to latest version but would guess at least to [v0.6.0](https://github.com/EnergieID/entsoe-py/releases/tag/V0.6.0), due to some refactoring in the generic parsing of timeseries.
