### ISSUE TITLE
Loads Having Only NaN Time Series in "status2023" Scenario

### ISSUE THREAD

**Issue by khelfen** [openego/powerd-data#225]
**Expected Behavior:**
Each load in the "status2023" scenario should have valid time series data that can be used for further analysis and simulation.

**Actual Behavior:**
Some loads within the scenario are associated with time series that are entirely NaN, rendering them unusable for any practical purpose. In my case 17 `central_heat` and `rural_heat` loads are affected.

**Suggested Actions:**
- @CarlosEpia or @ClaraBuettner could you check if this is also the case in the "status2019" scenario?
- A review of the data ingestion and processing pipeline for the "status2023" scenario might be necessary to identify and rectify the root cause of this issue.
- eTraGo should maybe check if all time series are valid and if all components have time series in the consistency check

**Comment by CarlosEpia** [comment]
Hi @khelfen We are experiencing the same in the status2019 scenario. In our case there are In total 8 loads filled entirely with NaN.

**Comment by khelfen** [comment]
Additional information: NaN values in the time series sometimes cause problems in the model formulation with Pyomo. I had to remove them in order to run eTraGo calculations.

```
ERROR:etrago.tools.utilities:Error: Traceback (most recent call last):
File "../etrago/tools/utilities.py", line 3073, in lopf_parallelization
network.lopf( 
File "../lib/python3.10/site-packages/deprecation.py", line 260, in _inner 
return function(*args, **kwargs)
File "../lib/python3.10/site-packages/pypsa/components.py", line 875, in lopf
return network_lopf(self, **args) 
File "../lib/python3.10/site-packages/pypsa/opf.py", line 2503, in network_lopf
network_lopf_build_model( 
File "../lib/python3.10/site-packages/pypsa/opf.py", line 2254, in network_lopf_build_model
define_nodal_balance_constraints(network, snapshots, transmission_losses) 
File "../lib/python3.10/site-packages/pypsa/opf.py", line 1603, in define_nodal_balance_constraints
l_constraint( 
File "../lib/python3.10/site-packages/pypsa/opt.py", line 202, in l_constraint 
v._data[i] = _GeneralConstraintData(constr_expr, v) 
File "../lib/python3.10/site-packages/pyomo/core/base/constraint.py", line 306, in __init__
self.set_value(expr)
File "../lib/python3.10/site-packages/pyomo/core/base/constraint.py", line 633, in set_value 
"lower bound (%s)." % (self.name, self._lower)) 
File "../lib/python3.10/site-packages/pyomo/core/base/component.py", line 345, in name 
return self.getname(fully_qualified=True) 
File "../lib/python3.10/site-packages/pyomo/core/base/component.py", line 867, in getname
return base + index_repr(self.index())
File "../lib/python3.10/site-packages/pyomo/core/base/component.py", line 793, in index
self._index is not NOTSET and
AttributeError: '_GeneralConstraintData' object has no attribute '_index'. Did you mean: 'index'? 
```
