### ISSUE TITLE
Airflow not working when scenario is eGon100RE

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#232]
When the scenario is set to eGon100RE, Airflow shows the error showed below:
`
Broken DAG: [/home/carlos/git/powerd-data/src/egon/data/airflow/dags/pipeline_status_quo.py]
Traceback (most recent call last):
  File "<string>", line 7, in __init__
  File "/home/carlos/git/powerd-data/src/egon/data/datasets/__init__.py", line 269, in __post_init__
    last = list(self.tasks.last)[0]
IndexError: list index out of range
`
It was found that the problem is related to the task ElectricalNeighbours. https://github.com/openego/powerd-data/blob/2676d99c26a5fb720ecbb1bdf418cb837e5970b6/src/egon/data/datasets/electrical_neighbours.py#L1732-L1748 eGon100RE is never mentioned.

**Comment by CarlosEpia** [comment]
It is still a pending task to adapt this [code](https://github.com/openego/powerd-data/blob/dev/src/egon/data/datasets/electrical_neighbours.py) to generate data for the eGon100RE?
