### ISSUE TITLE
No foreign gas buses eGon2035

### ISSUE THREAD

**Issue by CarlosEpia** [openego/powerd-data#35]
The task _gas_neighbours.eGon2035.tyndp-gas-generation_ is failing with the error message shown below. After checking the buses, it was found that there are 56 CH4 foreign buses for eGon100RE and 13 CH4 foreign buses for status2019, but none for eGon2035.

[2023-05-11 08:52:29,526] {taskinstance.py:901} INFO - Executing <Task(GasNeighbours (versioned)): gas_neighbours.eGon2035.tyndp-gas-generation> on 2023-05-05T14:00:18.321881+00:00
[2023-05-11 08:52:29,536] {standard_task_runner.py:54} INFO - Started process 26492 to run task
[2023-05-11 08:52:29,595] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'powerd-status-quo-processing-pipeline', 'gas_neighbours.eGon2035.tyndp-gas-generation', '2023-05-05T14:00:18.321881+00:00', '--job_id', '694', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline_status_quo.py', '--cfg_path', '/tmp/tmp1sgk33ek']
[2023-05-11 08:52:29,596] {standard_task_runner.py:78} INFO - Job 694: Subtask gas_neighbours.eGon2035.tyndp-gas-generation
[2023-05-11 08:52:29,651] {logging_mixin.py:120} INFO - Running <TaskInstance: powerd-status-quo-processing-pipeline.gas_neighbours.eGon2035.tyndp-gas-generation 2023-05-05T14:00:18.321881+00:00 [running]> on host at36
[2023-05-11 08:52:31,543] {logging_mixin.py:120} INFO - WARNING: No data returned by statement: 
 
        SELECT bus_id, ST_Buffer(geom, 1) as geom, country
        FROM grid.egon_etrago_bus
        WHERE scn_name = 'eGon2035'
        AND carrier = 'CH4'
        AND country != 'DE'
[2023-05-11 08:52:31,776] {taskinstance.py:1150} ERROR - index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/gas_neighbours/eGon2035.py", line 1394, in tyndp_gas_generation
    insert_generators(capacities)
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/gas_neighbours/eGon2035.py", line 501, in insert_generators
    get_foreign_gas_bus_id().loc[gen.loc[:, "index"]].values
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/gas_neighbours/eGon2035.py", line 91, in get_foreign_gas_bus_id
    buses.loc[i, "bus_id"] = distance[
IndexError: index 0 is out of bounds for axis 0 with size 0
[2023-05-11 08:52:31,777] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=powerd-status-quo-processing-pipeline, task_id=gas_neighbours.eGon2035.tyndp-gas-generation, execution_date=20230505T140018, start_date=20230511T065229, end_date=20230511T065231
[2023-05-11 08:52:34,376] {local_task_job.py:102} INFO - Task exited with return code 1

**Comment by ClaraBuettner** [comment]
Can we close this issue?

**Comment by CarlosEpia** [comment]
I think so. I proceed to close it.
