### ISSUE TITLE
chp.assign-heat-bus fails in SH run

### ISSUE THREAD

**Issue by ulfmueller** [openego/powerd-data#55]
```
WARNING: No data returned by statement: 
 
            SELECT * FROM
            supply.egon_chp_plants
            WHERE scenario = 'status2019'
            AND district_heating = True
[2023-05-24 10:00:46,538] {logging_mixin.py:120} WARNING - /home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/chp/__init__.py:124: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  unary_union = df.centroid.unary_union
[2023-05-24 10:00:46,544] {taskinstance.py:1150} ERROR - Columns must be same length as key
Traceback (most recent call last):
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/__init__.py", line 200, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/powerd/sh-powerd-data/powerd-data/src/egon/data/datasets/chp/__init__.py", line 181, in assign_heat_bus
    chp["district_heating_area_id"] = chp.apply(
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1351, in __setitem__
    super().__setitem__(key, value)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3602, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/powerd/sh-powerd-data/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3729, in _set_item_frame_value
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```

@ClaraBuettner can you tackle this? Or give me a hint?

**Comment by ClaraBuettner** [comment]
will be fixed in #58
