### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/powerd-data#62]
I tried to install powerd-data on the current `dev` but ran into an error related to the `logging` package.

That is also detected by the tox test (which actually already failed before, so this new error was hidden, see #52.):
```

   × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/runner/work/powerd-data/powerd-data/.tox/py38-nocov-linux/lib/python3.8/site-packages/setuptools/__init__.py", line 7, in <module>
          import _distutils_hack.override  # noqa: F401
        File "/home/runner/work/powerd-data/powerd-data/.tox/py38-nocov-linux/lib/python3.8/site-packages/_distutils_hack/override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "/home/runner/work/powerd-data/powerd-data/.tox/py38-nocov-linux/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 77, in do_override
          ensure_local_distutils()
        File "/home/runner/work/powerd-data/powerd-data/.tox/py38-nocov-linux/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 63, in ensure_local_distutils
          core = importlib.import_module('distutils.core')
        File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "/home/runner/work/powerd-data/powerd-data/.tox/py38-nocov-linux/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 22, in <module>
          from .dist import Distribution
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "/home/runner/work/powerd-data/powerd-data/.tox/py38-nocov-linux/lib/python3.8/site-packages/_virtualenv.py", line 90, in exec_module
          old(module)
        File "/home/runner/work/powerd-data/powerd-data/.tox/py38-nocov-linux/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 12, in <module>
          import logging
        File "/tmp/pip-install-cqwf5cfp/logging_ef555f03eeaa43beab138698506b54e6/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]
```

**Comment by ClaraBuettner** [comment]
It looks like logging is already installed per default (see https://stackoverflow.com/questions/71507457/how-to-install-logging-module). So I will just remove it from the list of dependencies.
